### ISSUE TITLE
Save settings button does not show being clicked on Firefox

### ISSUE THREAD

**Issue by kendoka15** [MalwareTech/BlueLiteBlocker#1]
At least on Firefox, when I click "Save Settings" after making a change, there is no indication that it was clicked. It still appears to work but it would be nice to have some kind of indication that the button works (also great job on the plugin Marcus)

**Comment by MalwareTech** [comment]
Adding something to the next version that will auto close the popup window on save

**Comment by MalwareTech** [comment]
Fixed in latest commit
