### ISSUE TITLE
Failed to load extension

### ISSUE THREAD

**Issue by TheHusseler** [MalwareTech/BlueLiteBlocker#13]
Error pops up when trying to load unpacked. Not sure what's going on here. 

```
File
~/Downloads/BlueLiteBlocker-0.0.0.9/BlueLiteBlocker
Error
Manifest file is missing or unreadable
Could not load manifest.
```

Chrome version: 114.0.5735.133
MacOS Monterey

**Comment by MalwareTech** [comment]
You need to rename either chrome_mainfest.json or firefox_manifest.json to manifest.json.

**Comment by TheHusseler** [comment]
That loaded it, thanks
