### ISSUE TITLE
Which API call intercepts pinned tweets?

### ISSUE THREAD

**Issue by roberrrt-s** [MalwareTech/BlueLiteBlocker#8]
Hi!

When inspecting the hook, it listens to the UserTweets API call to get "timelines" of users, but it does seem to skip the pinned tweet, do you have any idea how twitter extracts this?

All the best,
Robert

**Comment by i3p9** [comment]
It doesn't, look for the type `TimelinePinEntry` in the instruction array inside the response.

**Comment by roberrrt-s** [comment]
> It doesn't, look for the type `TimelinePinEntry` in the instruction array inside the response.

Ah, thank you!  Found it.
